JobCraft/Controllers/HomeController.cs
using JobCraft.Models;
using JobCraft.Repositories.Abstract;
using JobCraft.Repositories.Implementation;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace JobCraft.Controllers
{
    public class HomeController : Controller
    {
        private readonly IVacancyService _vacancyService;

        public HomeController(IVacancyService vacancyService)
        {
            _vacancyService = vacancyService;
        }

        public IActionResult Index()
        {
            var categories = Enum.GetValues(typeof(JobCategory))
                         .Cast<JobCategory>()
                         .Select(e => new SelectListItem
                         {
                             Value = e.ToString(),
                             Text = e.ToString()
                         })
                         .ToList();

            var locations = Enum.GetValues(typeof(Locations))
                                .Cast<Locations>()
                                .Select(e => new SelectListItem
                                {
                                    Value = e.ToString(),
                                    Text = e.ToString()
                                })
                                .ToList();

            ViewBag.Categories = categories;
            ViewBag.Locations = locations;
            var vacancies = _vacancyService.List();
            return View(vacancies);
        }

        public IActionResult Privacy()
        {
            return View();
        }
        [Route("job/{id:int}", Name = "jobdesc")]
        public async Task<IActionResult> JobDetails(int id)
        {
            var vacancy = _vacancyService.getById(id);
            return View(vacancy);
        }
    }
}

JobCraft/Controllers/JobsListController.cs
using JobCraft.Repositories.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace JobCraft.Controllers
{
    public class JobsListController : Controller
    {
        private readonly IVacancyService _vacancyService;

        public JobsListController(IVacancyService vacancyService)
        {
            _vacancyService = vacancyService;
        }
        public IActionResult Index(string title = "", string category = "", string location = "")
        {

            var vacancies = _vacancyService.FilterList(title, category, location);
            return View(vacancies);
        }

    }
}

JobCraft/Views/Home/Index.cshtml
@model JobCraft.Models.VacancyList
@{
    ViewData["Title"] = "ვაკანსიები";
}


<div class="contaienr-fluid banner">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-md-5 col-12">
            <p class="header-text">
                კარიერას თუ ახლა იწყებ, ეს ვაკანსიები შენთვისაა
            </p>
            <div class="filter-div col-lg-11 mt-5">
                <form asp-action="Index" asp-controller="JobsList" method="get">
                    <div class="container-fluid filter-inputs d-flex flex-wrap d-inline-flex align-items-center">
                        <input type="text" name="title" placeholder="რას ეძებ?" class="input-title">
                        <div class="category-input">
                            <label for="category"><i class="bi bi-briefcase"></i></label>
                            <select id="category" name="category">
                                <option value="">კატეგორია</option>
                                @foreach (var category in ViewBag.Categories)
                                {
                                    <option value="@category.Value">@category.Text</option>
                                }
                            </select>
                        </div>

                        <div class="location-input">
                            <label for="location"><i class="bi bi-geo-alt"></i></label>
                            <select id="location" name="location">
                                <option value="">ლოკაცია</option>
                                @foreach (var location in ViewBag.Locations)
                                {
                                    <option value="@location.Value">@location.Text</option>
                                }
                            </select>
                            <button type="submit" class="filter-btn">ძიება</button>
                        </div>
                    </div>

                </form>
            </div>

        </div>

        <div class="col-md-5 col-12">
            <img src="images/Doodle.png" class="img-fluid" />
        </div>
    </div>
</div>

<!--Vacancy List-->
<div class="container mt-5 VacancyList">
    <div class="row">

        <div class="col-md-4">
            d
        </div>
        <div class="col-md-8">
            <div class="titleVacancies">
                <h3>სტანდარტული ვაკანსიები</h3>
            </div>
            <div class="vacancy-list">


                @foreach (var vacancy in Model.Vacancies)
                {

                    <div class="vacancy-box border-1 border mt-4">
                        <div class="row">
                            <div class="col-lg-1 col-2">
                                <a href="#">
                                    <img src="/Uploads/@vacancy.LogoName" alt="Company Logo" style="width: 50px; height:50px; border-radius:5px; margin-top:5px">
                                </a>
                            </div>


                            <div class="col-10">
                                <div class="vacancy-title">
                                    <a asp-route="jobdesc" asp-route-id="@vacancy.Id">@vacancy.VacancyName</a>
                                </div>

                                <div class="vacancy-company d-flex">
                                    <i class="bi bi-house"></i>
                                    <a href="#">@vacancy.CompanyName</a>
                                </div>
                                <div class="vacancy-type d-flex">
                                    <i class="bi bi-briefcase"></i>
                                    <a href="#">@vacancy.JobCategory</a>
                                </div>

                                <div class="vacancy-location d-flex">
                                    <i class="bi bi-geo-alt"></i>
                                    <a href="#">@vacancy.Location</a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<a class="" asp-action="Index" asp-controller="JobsList" asp-route-title="ბანქო" asp-route-location="თბილისი" asp-route-category="">daawire</a>
<script src="~/js/mainPage.js"></script>

JobCraft/Views/Home/JobDetails.cshtml
@model JobCraft.Models.Vacancy
@{
    ViewData["Title"] = Model.VacancyName;
}
<div class="job-head">
    <div class="container-fluid">
        <div class="row">

            <div class="col-lg-2">
            </div>
            <div class="col-lg-8 col-12">
                <div class="row">
                    <div class="col-sm-8  d-flex flex-row">
                        <div class="job-img">
                            <img src="/Uploads/@Model.LogoName" alt="Company Logo" />
                        </div>
                        <div class="job-main-info">
                            <p class="job-main-title">@Model.VacancyName</p>
                            <p class="job-main-company">@Model.CompanyName</p>
                            <div class="job-main-desc d-flex flex-wrap">
                                <div class="job-main-desc-loc">
                                    <i class="bi bi-geo-alt"></i><a class="job-main-location">@Model.Location</a>
                                </div>
                                <div class="job-main-date-div">
                                    <i class="bi bi-clock-history"></i><a class="job-main-date">
                                        @Model.CreatedAt.ToString("dd/MM/yyyy")
                                    </a>
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4 d-flex flex-column vacancy-date-cv">
                        <div class="last-date mt-2">
                            განცხადების ვადა: @Model.EndsAt.ToString("dd/MM/yyyy")
                        </div>
                        <div class="send-cv-button mt-3">
                            <a class="btn">გააგზავნე რეზიუმე</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<div class="container-fluid vacancy-main mt-5">
    <div class="row">
        <div class="col-lg-2">

        </div>

        <div class="col-lg-10">
            <p class="vacancy-main-header ">განცხადების აღწერა</p>
            <div class="content-desc">
                @Html.Raw(Model.Content)
            </div>
        </div>
    </div>

</div>